import AppKit
import Carbon
import CryptoKit

class Clipboard {
  static let shared = Clipboard()

  private let pasteboard = NSPasteboard.general
  private var changeCount: Int
  private var timer: Timer?
  private var lastCapturedFingerprint: String?
  private var lastCapturedAt: Date?
  private var pendingWorkItem: DispatchWorkItem?
  private var lastChangeObservedAt: Date?

  private let supportedTypes: Set<NSPasteboard.PasteboardType> = [
    .fileURL,
    .html,
    .png,
    .rtf,
    .string,
    .tiff
  ]
  
  // TODO: Make these configurable via Settings
  private var enabledTypes: Set<NSPasteboard.PasteboardType> = [
    .fileURL, .html, .png, .rtf, .string, .tiff
  ]
  private var disabledTypes: Set<NSPasteboard.PasteboardType> { supportedTypes.subtracting(enabledTypes) }
  
  private let ignoredTypes: Set<NSPasteboard.PasteboardType> = [
    .autoGenerated,
    .concealed,
    .transient,
    .fromPastable // Ignore self
  ]

  init() {
    changeCount = pasteboard.changeCount
  }

  func start() {
    timer = Timer.scheduledTimer(
      timeInterval: 1.0, // Poll every 1 second
      target: self,
      selector: #selector(checkForChangesInPasteboard),
      userInfo: nil,
      repeats: true
    )
  }

  @objc
  func checkForChangesInPasteboard() {
    guard pasteboard.changeCount != changeCount else {
      return
    }

    let newChangeCount = pasteboard.changeCount
    let now = Date()
    let frontApp = NSWorkspace.shared.frontmostApplication?.bundleIdentifier ?? "unknown"
    let typesList = pasteboard.types?.map { $0.rawValue } ?? []
    #if DEBUG
    debugLog("pasteboard-change", [
      "changeCount": "\(changeCount)->\(newChangeCount)",
      "deltaMs": lastChangeObservedAt == nil ? "-" : "\(Int(now.timeIntervalSince(lastChangeObservedAt!) * 1000))",
      "frontApp": frontApp,
      "types": typesList.joined(separator: ", ")
    ])
    #endif
    lastChangeObservedAt = now
    changeCount = newChangeCount
    
    // Coalesce rapid pasteboard updates (some apps write in multiple passes)
    pendingWorkItem?.cancel()
    let workItem = DispatchWorkItem { [weak self] in
      self?.processPasteboardSnapshot()
    }
    pendingWorkItem = workItem
    DispatchQueue.main.asyncAfter(deadline: .now() + 0.15, execute: workItem)
  }

  @MainActor
  func copy(_ item: HistoryItem) {
    pasteboard.clearContents()
    for content in item.contents {
      if let type = NSPasteboard.PasteboardType(rawValue: content.type) as NSPasteboard.PasteboardType?,
         let value = content.value {
        pasteboard.setData(value, forType: type)
      }
    }
    pasteboard.setString("", forType: .fromPastable)
  }

  func paste() {
    // Force QWERTY keycode for V (kVK_ANSI_V = 9)
    let vCode = CGKeyCode(9)
    
    let source = CGEventSource(stateID: .combinedSessionState)
    // Disable local keyboard events while pasting
    source?.setLocalEventsFilterDuringSuppressionState(
      [.permitLocalMouseEvents, .permitSystemDefinedEvents],
      state: .eventSuppressionStateSuppressionInterval
    )
    
    let keyVDown = CGEvent(keyboardEventSource: source, virtualKey: vCode, keyDown: true)
    let keyVUp = CGEvent(keyboardEventSource: source, virtualKey: vCode, keyDown: false)
    
    keyVDown?.flags = .maskCommand
    keyVUp?.flags = .maskCommand
    
    keyVDown?.post(tap: .cgSessionEventTap)
    keyVUp?.post(tap: .cgSessionEventTap)
    
    // Play sound on paste only
    Task { @MainActor in
      self.playSound(reason: "paste")
    }
  }
  
  @MainActor
  func paste(_ item: HistoryItem) {
    copy(item)
    // Small delay to allow window to close if called sequentially
    DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
      self.paste()
    }
  }

  private func playSound(reason: String) {
    // Check Settings
    guard UserDefaults.standard.bool(forKey: "playSounds") else { return }
    #if DEBUG
    debugLog("sound", ["reason": reason])
    #endif
    
    // Play system sound "Tink"
    if let sound = NSSound(named: NSSound.Name("Tink")) {
        sound.play()
    } else {
        NSSound.beep()
    }
  }

  private func processPasteboardSnapshot() {
    let captureId = UUID().uuidString
    if let types = pasteboard.types {
      let typeSet = Set(types)
      if !typeSet.isDisjoint(with: ignoredTypes) {
        #if DEBUG
        debugLog("snapshot-skip", [
          "captureId": captureId,
          "reason": "ignoredTypes",
          "types": types.map { $0.rawValue }.joined(separator: ", ")
        ])
        #endif
        return
      }
    }

    // Read content
    var contents = [HistoryItemContent]()
    var hitTypes: [String] = []
    pasteboard.pasteboardItems?.forEach { item in
       // Simple reading logic for now
       for type in supportedTypes {
         if let data = item.data(forType: type) {
           contents.append(HistoryItemContent(type: type.rawValue, value: data))
           hitTypes.append(type.rawValue)
         }
       }
    }

    guard !contents.isEmpty else { return }

    let historyItem = HistoryItem(contents: contents)
    historyItem.application = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
    // Title and cachedPreviewText are now generated in init

    // De-dup fast consecutive identical copies (some apps trigger multiple pasteboard changes)
    let fingerprint = fingerprint(for: historyItem)
    let now = Date()
    #if DEBUG
    debugLog("snapshot", [
      "captureId": captureId,
      "contents": "\(contents.count)",
      "hitTypes": Array(Set(hitTypes)).joined(separator: ", "),
      "frontApp": historyItem.application ?? "unknown",
      "fingerprint": fingerprint,
      "deltaSinceLastMs": lastCapturedAt == nil ? "-" : "\(Int(now.timeIntervalSince(lastCapturedAt!) * 1000))"
    ])
    #endif
    if let last = lastCapturedFingerprint,
       last == fingerprint,
       let lastAt = lastCapturedAt,
       now.timeIntervalSince(lastAt) < 1.0 {
      #if DEBUG
      debugLog("snapshot-skip", [
        "captureId": captureId,
        "reason": "duplicate-fingerprint",
        "deltaMs": "\(Int(now.timeIntervalSince(lastAt) * 1000))",
        "fingerprint": fingerprint
      ])
      #endif
      return
    }
    lastCapturedFingerprint = fingerprint
    lastCapturedAt = now
    
    // Save to Storage
    #if DEBUG
    debugLog("before-store", [
      "captureId": captureId,
      "fingerprint": fingerprint,
      "contents": "\(contents.count)",
      "hitTypes": Array(Set(hitTypes)).joined(separator: ", "),
      "frontApp": historyItem.application ?? "unknown"
    ])
    #endif
    Task { @MainActor in
      Storage.shared.addOrUpdate(historyItem)
      // Signal UI to scroll to the new item
      AppState.shared.shouldScrollToTop = true
    }
  }

  private func fingerprint(for item: HistoryItem) -> String {
    if let text = item.text, !text.isEmpty {
      return "text:\(sha256(text.data(using: .utf8) ?? Data()))"
    }
    if !item.fileURLs.isEmpty {
      let joined = item.fileURLs.map { $0.absoluteString }.joined(separator: "\n")
      return "files:\(sha256(joined.data(using: .utf8) ?? Data()))"
    }
    if let imageData = item.imageData, !imageData.isEmpty {
      return "image:\(sha256(imageData))"
    }
    if let rtf = item.rtf?.string, !rtf.isEmpty {
      return "rtf:\(sha256(rtf.data(using: .utf8) ?? Data()))"
    }
    if let html = item.html?.string, !html.isEmpty {
      return "html:\(sha256(html.data(using: .utf8) ?? Data()))"
    }
    if let raw = item.contents.first(where: { $0.value != nil })?.value {
      return "raw:\(sha256(raw))"
    }
    return "empty:\(UUID().uuidString)"
  }

  private func sha256(_ data: Data) -> String {
    let digest = SHA256.hash(data: data)
    return digest.map { String(format: "%02x", $0) }.joined()
  }

  #if DEBUG
  private func debugLog(_ tag: String, _ fields: [String: String]) {
    let ts = ISO8601DateFormatter().string(from: Date())
    let payload = fields.map { "\($0.key)=\($0.value)" }.joined(separator: " ")
    print("[Clipboard][\(tag)] \(ts) \(payload)")
  }
  #endif
}
